### ISSUE TITLE
Use relative abundance to calculate Bray-Curtis index

### ISSUE THREAD

**Issue by tobiasgf** [gbif/edna-tool-ui#104]

**Comment by thomasstjerne** [comment]
Isn´t this sufficient?
<img width="1046" alt="Screenshot at May 13 14-17-27" src="https://github.com/gbif/edna-tool-ui/assets/1666484/ca8563ff-581a-4e38-a9d7-8226a09e4344">

**Comment by tobiasgf** [comment]
That is probably fine. The question I got was actually about whether the BC dissimilarities were calculated on relative abundances. I believe we are calculating the BC based on the raw read counts, right? I may be best practice to convert to relative abundances (in sample) first. Would that be feasible?

**Comment by thomasstjerne** [comment]
It looks like we do this: https://github.com/gbif/edna-tool-ui/issues/2#issuecomment-1717637957
i.e.

> taking the fourth root of each value (x^0.25) is a quick and acceptable solution.

**Comment by tobiasgf** [comment]
That is to downweight the influence of high numbers. But to make sample-to-sample comparisons fair, the sampling effort (read counts per sample) need to be similar, that can be done by resampling (to even depth) or scaling. I suggest to do the last, by dividing the read counts by sample total read count (=relative abundances)
