### ISSUE TITLE
Make it possible to associate a network with a dataset (e.g. OBIS)

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/edna-tool-ui#109]
How is this done with the Legacy API 🤔

**Comment by mike-podolskiy90** [comment]
IPT API:
GET https://gbrds.gbif-uat.org/registry/network.json - all networks
GET https://gbrds.gbif-uat.org/registry/resource/<dataset_key>/network - resource networks
POST https://gbrds.gbif-uat.org/registry/resource/<dataset_key>/network/<network_key> - add network
DELETE https://gbrds.gbif-uat.org/registry/resource/<dataset_key>/network/<network_key> - delete network

v1 API:
POST https://api.gbif-uat.org/v1/network/{key}/constituents/{datasetKey}
DELETE https://api.gbif-uat.org/v1/network/{key}/constituents/{datasetKey}
