### ISSUE TITLE
Make sure that the "term"s agreement of the tool is in sync with IPT (other publishing routes)

### ISSUE THREAD

**Issue by tobiasgf** [gbif/edna-tool-ui#111]
If the tool has an "accept terms" tick-box, this should mirror (in function be the same) the procedure when publishing through other channels.
I am not sure if there are actually more "I accept the terms" steps than when a publisher accepts the publisher agreement upon endorsement.

**Comment by timrobertson100** [comment]
When clicking the button to register GBIF, please have it say

> Confirm that you have read and agreed to the [GBIF Terms](https://www.gbif.org/terms)

This will mirror the [IPT functionality](https://github.com/gbif/ipt/issues/2520)
