### ISSUE TITLE
Is there an estimated waiting time for the "Assigning taxonomy" function?

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/edna-tool-ui#49]
Is there an approximate time range to the assigning taxonomy function with the edna_template? I have been trying to use it and it is processing for more than a day as in this example: [https://edna-tool.gbif-uat.org/dataset/cdb2b4ae-53a9-47b0-8a87-be64142ba68d/process](https://edna-tool.gbif-uat.org/dataset/cdb2b4ae-53a9-47b0-8a87-be64142ba68d/process)

Maybe it is related to the [sequence annotation tool](https://www.gbif.org/tools/sequence-id) not working properly. I tested it with my data and some of the test data and it always shows "sequences could not be matched"
<img width="1342" alt="image" src="https://github.com/gbif/edna-tool-ui/assets/63795703/24ccb9b6-eb11-44a3-b2fb-5a7fa802cb53">

I do not know if this process depend on internet connection from the user part, but if this is done at GBIF servers/web tool maybe this part can be complemented with a small message like "1000 records typically take up to x hours"
<img width="1011" alt="image" src="https://github.com/gbif/edna-tool-ui/assets/63795703/925cc7f9-bb25-484c-854d-22db7cede160">

**Comment by tobiasgf** [comment]
Hi Esteban. Thanks again for your input and feedback. Can you send the 4 fasta sequences that gives you trouble (in SeqID tool) to me in our email thread? Are they they from the same dataset that gives problems in the "eDNA converter tool"?
As far as I remember, we did a test, where we were able to match many thousand sequences in a a few hours. Internet speed should not be a factor.

**Comment by tobiasgf** [comment]
The problem was due to the SeqID tool being offline as you also suggested. Should be fixed now.
I'll leave the issue open as it would maybe be valuable to give an _estimated remaining time_ for the sequence matching, and not just the progress bar. And maybe also an option to kill the seq-matching process.
