### ISSUE TITLE
Is it possible to map abiotic measurements in this tool?

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/edna-tool-ui#54]
I was wondering if it is possible to map abiotic measurements, most of our eDNA datasets have at least some abiotic measurements (pH, conductivity, temperature, etc). 
In the mapping section I couldn't find measurementType/measurementValue fields, I think that would be really valuable to include. 

From the publishing guide and the slides about the tool (where you can see pH as a column) I understand that abiotic measurements are encouraged in eDNA datasets, but maybe I am wrong.

If those elements will not be available in the tool, perhaps it can be explained in the FAQ section.

Thanks in advance and sorry if this was addressed before, but I could find information about it.

**Comment by thomasstjerne** [comment]
Hi @EstebanMH-SiB 
You can actually have any column in the sample file, and it will be stores in the BIOM files. However, we are so far only mapping to fields from [dwc:occurrence](https://rs.gbif.org/core/dwc_occurrence_2022-02-02.xml) and [DNA Derived Data](https://rs.gbif.org/extension/gbif/1.0/dna_derived_data_2022-02-23.xml). This means that currently, the fields you mention will not make it to the DWC archive. 
How ever, we are thinking about the possibility to also produce [extended measurements and facts](https://rs.gbif.org/extension/obis/extended_measurement_or_fact_2023-08-28.xml) at a later stage

**Comment by tobiasgf** [comment]
Consider just converting unmapped fields from the sample-sheet to eMoF.
A quick start could be by simply "melting" the remaining unmapped fields in the sample-sheet (broad to tall format): using the field name/header as measurementType and the cell value as measurementValue.
A next step could then be to allow the user to manually add measurementUnit afterwards.

Links the to relevant occurrences/events should be added in the processing.
Look at e.g. https://www.gbif.org/occurrence/4422934732
