### ISSUE TITLE
Should deleting a file erase mapping and processing of data?

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/edna-tool-ui#58]
I am wondering what is the best way to proceed when you are in step 3, find an error and return to step 1 to delete your files and restart the process. Maybe it can follow the same path as IPT, that when you delete your original files the mapping process also is automatically erased.

I deleted the original files in this [dataset](https://edna-tool.gbif-uat.org/dataset/561e99c8-10db-4860-af9f-f14f1ed84d80/process) and when I reuploaded corrected files the processed data showed the same previous mistakes, looks like it is "stuck" with the previous information.

The other option is to keep the mapping but making sure information will be read again properly.

**Comment by tobiasgf** [comment]
I noticed the same yesterday. You can argue, that going back to step 1 is (should be) something else that pressing "new dataset". But, my first thought was also that the mapping should be wiped. I wonder what happens if the re-uploaded data conflicts with the stuck mapping...?

**Comment by thomasstjerne** [comment]
Not sure if we should erase the BIOM files(?). You would need to press the "re-process" button to get rid of the error messages. This will re-generate the BIOM files and create new error reports.
But in this specific case, you would first have to go back to the [mapping step](https://edna-tool.gbif-uat.org/dataset/561e99c8-10db-4860-af9f-f14f1ed84d80/term-mapping) and create mappings for the `id`s (both sample and taxon.)
